package com.amadeus.droolsfeature.rules 

import com.amadeus.model.*
import java.util.ArrayList

declare  BzrFlightDeclare
    number : int 
    airline : String 
    matchList : java.util.ArrayList 
end

 

declare  BzrFlightMatchDeclare
    name : String 
    lom : int 
end

 

declare  Booking
    @release( 0 )
    customer : String 
    flight : BzrFlightDeclare 
    returnFlight : BzrFlightDeclare 
end

 

function void addMatch( BzrFlightDeclare k, String keywordName, int levelOfMatch ) {
    BzrFlightMatchDeclare match = new BzrFlightMatchDeclare();
    match.setName(keywordName);
    match.setLom(levelOfMatch);
    if (k.getMatchList() == null) k.setMatchList(new java.util.ArrayList()); 
          k.getMatchList().add(match);
}

 

 

function BzrFlightMatchDeclare createBzrFlightMatchDeclare(String name){
    BzrFlightMatchDeclare bfmd = new BzrFlightMatchDeclare();
    bfmd.setName(name);
    return bfmd;

}


rule "eval rule"
no-loop 
salience 10000
dialect "mvel" 
when
eval(name == "toto" && customer == "titi")
or eval(name == "toto" && customer == "titi")
then
 insert(f);
  System.out.println("yes");
end 

rule "and rule"
no-loop 
salience 10000
dialect "mvel" 
when
b:Booking (this != null, f:flight != null)
then
 insert(f);
  System.out.println("yes");
end 

rule "or rule"
no-loop 
salience 10000
dialect "mvel" 
when
Booking(customer == "Dupont")
or Booking(customer == "Martin")
b:Booking (this != null, f:flight != null)
then
 insert(f);
  System.out.println("yes");
end 

rule "or rule with eval"
no-loop 
salience 10000
dialect "mvel" 
when
Booking(customer == "Dupont")
or Booking(customer == "Martin")
then
 insert(f);
  System.out.println("yes");
end 

